config/routes.rb
Rails.application.routes.draw do


  # resources :reviews, only: [ :index, :new, :create, :edit, :update, :delete ]

  resources :bookings, only: [ :index, :show, :update, :edit, :delete ] do
    resources :reviews, only: [ :new, :create]
end

  get '/search', to: 'pages#search'

  get "user/dashboard", to: "users#dashboard"


  resources :venues, only: [ :index, :show, :search, :new, :create, :edit, :update ] do
    resources :bookings, only: [ :create ]
  end

  devise_for :users

  root to: 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user

  belongs_to :venue
  has_many :reviews, dependent: :delete_all

  validates :date, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  has_one :user , through: :booking

  validates :content, presence: true
  validates :rating, presence: true

end

app/models/user.rb
class User < ApplicationRecord
has_many :venues

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookings

  validates :name, presence: true

end

app/models/venue.rb
class Venue < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :users, through: :bookings
  has_many :reviews, through: :bookings

  validates :name, presence: true
  validates :capacity, presence: true
  validates :price, presence: true
  validates :location, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :category, presence: true
  mount_uploader :photo, PhotoUploader
    geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_address?

  # include PgSearch
  # pg_search_scope :search,
  #   against: [ :name, :description, :location, :category, :address ],
  #   using: {
  #     tsearch: { prefix: true }
  #   }
  include AlgoliaSearch
  algoliasearch per_environment: true do
    attribute :name, :location, :address, :description, :category
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
   devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show]
  before_action :set_venue, only: [:create]

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
    authorize @booking

  end

  def create
    @booking = Booking.new(booking_params)
    #@booking = current_user.bookings.build(booking_params) -old formula
    @booking.user = current_user
    @booking.venue = @venue
    authorize @booking

    if @booking.save
      redirect_to user_dashboard_path, notice: "your booking is now confirmed"
    else
      redirect_back fallback_location: root_path, alert: "Could not save this booking"
    end
  end

  def show
    @review = @booking.reviews.new

    authorize @review

  end

  def update

  end

  def edit

  end

  def destroy
    @booking.destroy
    redirect_to @booking
  end

  private


  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:date)
  end

  def set_venue
    @venue = Venue.find(params[:venue_id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :search]

  def home
    @venues = Venue.all
  end

  def search

    # if params[:search].present?
    #   @venues = Venue.search(params[:search])
    # else
    #   @venues = Venue.all
    # end
    @venues = Venue.all.where(name: params[:search])
    @venues_map = @venues.where.not(latitude: nil, longitude: nil)

    @markers = @venues_map.map do |venue|
      {
        lat: venue.latitude,
        lng: venue.longitude,
      }
    end
  end


  def results
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
    authorize @review
  end

  def create
    # @booking.venue = @venue
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    authorize @review
    if @review.save
      redirect_to venue_path(@booking.venue)
    else
      render :new
    end
  end

  # def create
  #   # [...]
  #   if @review.save
  #     respond_to do |format|
  #       format.html { redirect_to _path(@restaurant) }
  #       format.js  # <-- will render `app/views/reviews/create.js.erb`
  #     end
  #   else
  #     respond_to do |format|
  #       format.html { render 'venues/show' }
  #       format.js  # <-- idem
  #     end
  #   end
  # end

  def edit
  end

  def update
  end

  def destroy
    @review.destroy
    redirect_to @booking
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def dashboard
   authorize current_user
  end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show, :search]

  def index
    #@venues = Venue.all
    @venues = policy_scope(Venue).order(created_at: :desc)
  end

  def show
    @booking = Booking.new
    @reviews = @venue.reviews
  end


  def new
    @venue = Venue.new
    authorize @venue
  end

  def create
    @venue = Venue.new(venue_params)
    @venue.user = current_user
    authorize @venue
    if @venue.save
      redirect_to venue_path(@venue)
    else
      render :new
    end
  end

  def edit
    authorize @venue
  end

  def update
    @venue.update(venue_params)
    if @venue.save
      redirect_to venue_path(@venue)
    else
      render :edit
    end
  end

  def destroy
    @venue.destroy
    redirect_to venues_path
  end



  private

  def set_venue
    @venue = Venue.find(params[:id])
    authorize @venue
  end

  def venue_params
    params.require(:venue).permit(:name, :capacity, :price, :location, :address, :description, :category, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/delete.html.erb
<h1>Bookings#delete</h1>
<p>Find me in app/views/bookings/delete.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/bookings/show.html.erb
<div class="row venue_form">
  <h1>Leave us a review</h1>
  <br>
  <%= render 'reviews/form'%>
</div>
<center><%= link_to 'Home', root_path %><center>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Karla" rel="stylesheet">

    <title>Party_Places</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>


    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag "application" %>


      <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>

    <%= javascript_pack_tag "map" %> <!-- add this line -->
    <script src="https://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js"></script>
    <script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.min.js"></script>

  </body>
</html>

app/views/pages/home.html.erb
<div id="landing-header">
  <h1><strong>PARTY PLACES</strong></h1>
  <h3><strong>Make your night unforgettable</strong></h3>
  <!-- HTML Markup -->
  <%= form_tag search_path, method: :get do %>
<div class="aa-input-container" id="aa-input-container">
    <input type="search" id="aa-search-input" class="aa-input-search" placeholder="Search" name="search" autocomplete="off" />
    <svg class="aa-input-icon" viewBox="654 -372 1664 1664">
        <path d="M1806,332c0-123.3-43.8-228.8-131.5-316.5C1586.8-72.2,1481.3-116,1358-116s-228.8,43.8-316.5,131.5  C953.8,103.2,910,208.7,910,332s43.8,228.8,131.5,316.5C1129.2,736.2,1234.7,780,1358,780s228.8-43.8,316.5-131.5  C1762.2,560.8,1806,455.3,1806,332z M2318,1164c0,34.7-12.7,64.7-38,90s-55.3,38-90,38c-36,0-66-12.7-90-38l-343-342  c-119.3,82.7-252.3,124-399,124c-95.3,0-186.5-18.5-273.5-55.5s-162-87-225-150s-113-138-150-225S654,427.3,654,332  s18.5-186.5,55.5-273.5s87-162,150-225s138-113,225-150S1262.7-372,1358-372s186.5,18.5,273.5,55.5s162,87,225,150s113,138,150,225  S2062,236.7,2062,332c0,146.7-41.3,279.7-124,399l343,343C2305.7,1098.7,2318,1128.7,2318,1164z" />
    </svg>
</div>
<% end %>


<!-- Initialize autocomplete menu -->
   <script src="https://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js"></script>
    <script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.min.js"></script>

<script>
var client = algoliasearch('W9N3LUO41T', '8c8058b3a8bcb425bf64c162de5d5880');
var index = client.initIndex('Venue_development');
//initialize autocomplete on search input (ID selector must match)
autocomplete('#aa-search-input',
{ hint: false }, {
    source: autocomplete.sources.hits(index, {hitsPerPage: 5}),
    //value to be displayed in input control after user's suggestion selection
    displayKey: 'name',
    //hash of templates used when rendering dataset
    templates: {
        //'suggestion' templating function used to render a single suggestion
        suggestion: function(suggestion) {
          return '<span>' +
            suggestion._highlightResult.name.value + '</span><span>' +
            suggestion._highlightResult.location.value + '</span>';
        }
    }
});
</script>

  <br>
  <br>
  <br>
  <br>
</div>
<ul class="slideshow">
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
</ul>
<br>
<br>
<br>
<br>
<br>
<h3><strong>Popular Party Places</strong></h3>
<%= render  @venues %>

app/views/pages/search.html.erb
<div class="search-wrapper">
  <div class="search-left col-xs-8">
    <br>
    <%= render 'shared/searchbar' %>
    <br>
    <%= render @venues %>
  </div>
  <div class="search-right col-xs-4">
    <div
      id="map"
      style="
      width: 100%; height: 100%;"
      data-markers="<%= @markers.to_json %>"
    ></div>
  </div>
  <br>
  <center><%= link_to 'Home', root_path %></center>
  <br>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([ @booking, @review ]) do |form| %>
  <%= form.input :content %>
    <%= form.input :rating %>
  <%= form.button :submit %>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>

app/views/shared/_card.html.erb
<div class="cards-container col-xs-12 col-sm-6 col-lg-4 card-wrapper padded-top">

  <!-- Card Image -->
  <div class="card-image">
    <div class="wishlist-rounded wishlist-rounded-white text-center">
      <a href="#">
        <!-- Inline SVG -->
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="3430 1212 18 15.978" class="wishlist-icon wishlist-icon empty">
          <defs>
          </defs>
          <path id="Path_229" data-name="Path 229" class="cls-1" d="M13.237.5a3.777,3.777,0,0,0-2.523.995A6.534,6.534,0,0,0,8.988,3.452,6.485,6.485,0,0,0,7.262,1.488a3.676,3.676,0,0,0-.31-.25A3.753,3.753,0,0,0,4.738.5C2.393.5.443,2.78.489,5.593A5.73,5.73,0,0,0,.653,6.937a5.629,5.629,0,0,0,.382,1.107c1.878,4.269,7.952,7.372,7.952,7.372s6.075-3.1,7.952-7.372a6.093,6.093,0,0,0,.382-1.107,5.773,5.773,0,0,0,.165-1.344C17.54,2.78,15.589.5,13.237.5Z" transform="translate(3430.012 1212)"></path>
        </svg>
      </a>
    </div>
  </div>


  <!-- Card Bottom Row -->


  <!-- Card Rating and Review -->
  <div class="card-rating-reviews">
    <div class="card-row">
      <span class="card-average-rating">
        <span class="star-icon full">☆</span>
        <span class="star-icon full">☆</span>
        <span class="star-icon full">☆</span>
        <span class="star-icon full">☆</span>
        <span class="star-icon">☆</span>
      </span>
      <span class="card-reviews-count">
        &middot; 8 reviews
      </span>
    </div>
  </div>

  <!-- Card Link -->
  <a href="" class="card-link"></a>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form.html.erb
<div class="row venue_form">
  <%= simple_form_for @venue do |f| %>
  <%= f.input :name, placeholder:"The Lounge"%>
  <%= f.input :capacity, placeholder:"50 people" %>
  <%= f.input :price, placeholder:"250 €" %>
  <%= f.input :location, placeholder:"Paris" %>
  <%= f.input :address, placeholder:"18 Rue Beautreillis, 75004 Paris, France" %>
  <%= f.input :description, placeholder:"Lounge for private events with a capacity to receive 50 people. Tables and chairs are available." %>
  <%= f.input :category, placeholder:"Lounges" %>
  <%= f.input :photo, placeholder:"upload venues picute" %>
  <%= f.submit "Add venue", class: "btn btn-primary btn-block" %>
  <% end %>
</div>
<center><%= link_to 'Back', search_path %><center>

app/views/shared/_jumbotron.html.erb
<div class="jumbotron" style="background-image: url('<%= @venue.photo.url %>')" >
</div>
<div class="container">
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <% end %>

  <!-- Right Navigation -->

  <div class="navbar-wagon-right">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Search", search_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Add a Venue", new_venue_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/joemonteiro", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_dashboard_path do %>
                <i class="fa fa-user"></i> <%= t(".dashboard", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<div class="searchbar">
  <%= form_tag search_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Search for a venue"
    %>
  <% end %>

</div>

app/views/shared/_venue_form.html.erb
<div class="row venue_form" >

  <h4><strong>€<%= @venue.price%></strong> per night</h4>

  <%= simple_form_for @venue do |f| %>
  <%  f.input :venue_id, :as => :hidden, :input_html => { :value => @venue.id } %>
  <%= f.input :capacity %>
  <% end %>

  <%= simple_form_for [@venue, @booking] do |f| %>
  <%  f.input :venue_id, :as => :hidden, :input_html => { :value => @venue.id } %>
  <%= f.input :date, as: :date %>
  <%= f.submit "Book venue", class: "btn btn-primary btn-block" %>
  <%end%>
</div>

app/views/users/dashboard.html.erb
<br>
<center><h2>Your Bookings</h2></center>
<br>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">Address</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% current_user.bookings.each do |booking| %>
      <td> <%= booking.venue.name %> </td>
      <td> <%= booking.venue.price %> </td>
      <td> <%= booking.venue.address %> </td>
      <td> <%= link_to "Add a Review" , booking %></td>
      <td> <%= link_to "Show Venue" , venue_path(booking.venue) %></td>


    </tr>
    <% end %>
    <tr>
  </tbody>
</table>
<br>
<center><%= link_to 'Home', root_path %></center>
<br>

app/views/venues/_venue.html.erb
<div class="card-margin col-xs-12 col-sm-6 col-lg-4">

<div class="cards-container card-wrapper padded-top">
  <div class="card-image" style="background-image: url('<%= venue.photo.url %>')">
      <div class="wishlist-rounded wishlist-rounded-white text-center">
        <a href="#">
          <!-- Inline SVG -->
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="3430 1212 18 15.978" class="wishlist-icon wishlist-icon empty">
            <defs>
            </defs>
            <path id="Path_229" data-name="Path 229" class="cls-1" d="M13.237.5a3.777,3.777,0,0,0-2.523.995A6.534,6.534,0,0,0,8.988,3.452,6.485,6.485,0,0,0,7.262,1.488a3.676,3.676,0,0,0-.31-.25A3.753,3.753,0,0,0,4.738.5C2.393.5.443,2.78.489,5.593A5.73,5.73,0,0,0,.653,6.937a5.629,5.629,0,0,0,.382,1.107c1.878,4.269,7.952,7.372,7.952,7.372s6.075-3.1,7.952-7.372a6.093,6.093,0,0,0,.382-1.107,5.773,5.773,0,0,0,.165-1.344C17.54,2.78,15.589.5,13.237.5Z" transform="translate(3430.012 1212)"></path>
          </svg>
        </a>
      </div>
    </div>


  <!-- Card Bottom Row -->
    <div class="card-details">
    <div class="card-row">
      <span class="card-price"> €<%= venue.price %> |</span>
      <span class="card-name"><%= venue.name %></span>
    </div>
    <div class="card-row">
      <span class="card-location"><%= venue.location %></span>
    </div>
  </div>

  <!-- Card Rating and Review -->
  <%= link_to venue_path(venue), anchor: "#reviews" do %>
  <div class="card-rating-reviews">
    <div class="card-row">
      <span class="card-average-rating">
        <span class="star-icon full">☆</span>
        <span class="star-icon full">☆</span>
        <span class="star-icon full">☆</span>
        <span class="star-icon full">☆</span>
        <span class="star-icon">☆</span>
      </span>
      <span class="card-reviews-count">
        &middot; <%= venue.reviews.length %>
      Reviews</span>
    </div>
  </div>
  <% end %>

  <!-- Card Link -->
  <%= link_to venue, class: "card-link" do %>
  <% end %>

</div>

</div>

app/views/venues/edit.html.erb
<div class="col-sm-4 col-sm-offset-4">
  <h2>Edit your Venue</h2>

<%= render 'shared/form' %>
</div>
<center><%= link_to 'Home', root_path %><center>

app/views/venues/index.html.erb
<div class="container">

  <div class="container">
    <h1>My Venues</h1>
    <% @venues.each do |venue| %>
      <%= render  @venues %>
        <div>
          <% if policy(venue).edit? %>
            <%= link_to "edit", edit_venue_path(venue), class: "btn btn-primary btn-sm" %>
          <% end %>
          <% if policy(venue).destroy? %>
            <%= link_to "delete", venues_path, method: :delete, data: { confirm: "Are you Sure?" }, class: "btn btn-primary btn-sm" %>
          <% end %>
       </div>
    <% end %>
  </div>
</div>


  <% if policy(Venue).new? %>
      <%= link_to "New Venue", new_venue_path, class: "btn btn-primary" %>
  <% end %>

app/views/venues/new.html.erb
<center><h2>Add your Venue</h2></center>
<%= render 'shared/form' %>

app/views/venues/show.html.erb
<%= render 'shared/jumbotron' %>
<div class="container">
  <div class="col-xs-7">

    <h2>
      <strong> <%=@venue.name %></strong>
      <hr>
    </h1>
    <div class="d-inline categories">
      <i class="fas fa-building"></i>
      <%= @venue.category%>&nbsp&nbsp
      <i class="fas fa-map-marker"></i>
      <%= @venue.location %>&nbsp&nbsp&nbsp
      <i class="fas fa-users"></i>
      Capacity: <%= @venue.capacity %>&nbsp

      <hr>
      <p>
        <br>
        <%= @venue.description %>
        <br>
      </p>

    </div>

    <div>
      <h3><strong>Reviews</strong></h3>


      <% @reviews.each  do |review| %>
      <div class="message">
  <img class="avatar-large" src="https://kitt.lewagon.com/placeholder/users/joemonteiro">
        <div class="message-name">
          <h3><%= current_user.name%></h3>
        </div>
        <div class="message-body">
          "<%= review.content %>"
        </div>
        <div>
          <%= review.rating %> <i class="fas fa-star"></i>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <div class="col-xs-5">
    <%= render 'shared/venue_form' %>
  </div>
</div>

<center><%= link_to 'home', root_path %><center>